services:  
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: bnsuser
      POSTGRES_PASSWORD: bnspassword
      POSTGRES_DB: bnsdb
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build:
      context: .
      dockerfile: src/Bns.Api/Dockerfile
    ports:
      - "5000:80"
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
    volumes:
      - ./src/Bns.Api:/app
      - ./src/Bns.Application:/src/Bns.Application
      - ./src/Bns.Domain:/src/Bns.Domain
    working_dir: /app
  vuetify:
    build:
      context: ./src/Bns.Vuetify
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./src/Bns.Vuetify:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=password
    volumes:
      - clickhouse_data:/var/lib/clickhouse
  keycloak:
    build:
      context: .
      dockerfile: ./keycloak-certs/Dockerfile
    image: quay.io/keycloak/keycloak:24.0.2
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/bnsdb
      KC_DB_USERNAME: bnsuser
      KC_DB_PASSWORD: bnspassword
      JAVA_OPTS: -Djavax.net.ssl.trustStore=/etc/pki/ca-trust/extracted/java/cacerts -Djavax.net.ssl.trustStorePassword=changeit -Dcom.sun.jndi.ldap.object.disableEndpointIdentification=true  # last is because wrong sertificate. DELETE on release
      # KC_HOSTNAME_URL: http://localhost:8082
      # KC_HOSTNAME: localhost
      # KC_HOSTNAME_PORT: 8082
      # KC_HOSTNAME_STRICT: false
      # KC_HOSTNAME_STRICT_HTTPS: false
      # KC_HTTP_ENABLED: true
      #KC_PROXY: edge
    ports:
      - "8083:8080"
    depends_on:
      - db
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - keycloak
    environment:
      - NGINX_SUBFILTER_OUTPUT=on
volumes:
  postgres_data:
  clickhouse_data:
