/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    CustomDt: typeof import('./components/Datatables/CustomDt.vue')['default']
    DataTableRaw: typeof import('./components/Datatables/DataTableRaw.vue')['default']
    Dt: typeof import('./components/Datatables/Dt.vue')['default']
    DtCheckbox: typeof import('./components/Datatables/DtCheckbox.vue')['default']
    DtDatatables: typeof import('./components/Datatables/DtDatatables.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MyDt: typeof import('./components/Datatables/MyDt.vue')['default']
    ReactiveDataTable: typeof import('./components/Datatables/ReactiveDataTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    'СustomDt': typeof import('./components/Datatables/СustomDt.vue')['default']
  }
}
