// <auto-generated />
using System;
using Bns.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bns.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250724123451_add_Users_Language_UserSettings")]
    partial class add_Users_Language_UserSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bns.Domain.DataSources.DataSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ConfigurationId")
                        .HasColumnType("uuid")
                        .HasColumnName("ConfigurationId");

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("connection_string");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modify_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId");

                    b.ToTable("data_source");
                });

            modelBuilder.Entity("Bns.Domain.DataSources.DataSourceOlapConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowWritebackOnAggregationLevel")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_writeback_on_aggregation_level");

                    b.Property<int>("FiscalOffset")
                        .HasColumnType("integer")
                        .HasColumnName("fiscal_offset");

                    b.Property<bool>("Impersonate")
                        .HasColumnType("boolean")
                        .HasColumnName("impersonate");

                    b.Property<bool>("LoadMemberCodeProperties")
                        .HasColumnType("boolean")
                        .HasColumnName("load_member_code_properties");

                    b.Property<int>("LoadMembersCount")
                        .HasColumnType("integer")
                        .HasColumnName("load_members_count");

                    b.Property<int>("PoolSize")
                        .HasColumnType("integer")
                        .HasColumnName("pool_size");

                    b.Property<bool>("PoolingEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("use_fiscal_offset");

                    b.Property<bool>("UseOlapNotes")
                        .HasColumnType("boolean")
                        .HasColumnName("use_olap_notes");

                    b.Property<int>("WritebackLeafLimit")
                        .HasColumnType("integer")
                        .HasColumnName("writeback_leaf_limit");

                    b.HasKey("Id");

                    b.ToTable("data_source_olap_config");
                });

            modelBuilder.Entity("Bns.Domain.Users.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("Bns.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_time");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delete_time");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("Locked")
                        .HasColumnType("boolean")
                        .HasColumnName("locked");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modify_time");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<Guid>("SettingsId")
                        .HasColumnType("uuid")
                        .HasColumnName("settings_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("SettingsId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Bns.Domain.Users.UserSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AutomaticCalculation")
                        .HasColumnType("boolean")
                        .HasColumnName("automatic_calculation");

                    b.Property<string>("DimensionPresets")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dimension_presets");

                    b.Property<string>("DimensionViewDisplayType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dimension_view_display_type");

                    b.Property<bool>("DisplayPanelCode")
                        .HasColumnType("boolean")
                        .HasColumnName("display_panel_code");

                    b.Property<bool>("DisplayZeros")
                        .HasColumnType("boolean")
                        .HasColumnName("display_zeros");

                    b.Property<bool>("HighlightActiveRow")
                        .HasColumnType("boolean")
                        .HasColumnName("highlight_active_row");

                    b.Property<int?>("LanguageId")
                        .HasColumnType("integer")
                        .HasColumnName("language_id");

                    b.Property<bool>("LoadNotes")
                        .HasColumnType("boolean")
                        .HasColumnName("load_notes");

                    b.Property<bool>("MinimalizeMenu")
                        .HasColumnType("boolean")
                        .HasColumnName("minimalize_menu");

                    b.Property<bool>("ModifyVersionFacts")
                        .HasColumnType("boolean")
                        .HasColumnName("modify_version_facts");

                    b.Property<bool>("PreferUserPanels")
                        .HasColumnType("boolean")
                        .HasColumnName("prefer_user_panels");

                    b.Property<bool>("RemoveNullRowsInSnapshot")
                        .HasColumnType("boolean")
                        .HasColumnName("remove_null_rows_in_shanpshot");

                    b.Property<string>("Skin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("skin");

                    b.Property<string>("StartupDashboard")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("startup_dashboard");

                    b.Property<bool>("SuppressNullRows")
                        .HasColumnType("boolean")
                        .HasColumnName("supress_null_rows");

                    b.Property<bool>("UndoEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("undo_enabled");

                    b.Property<string>("UseCurrentDate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("use_current_date");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("user_settings");
                });

            modelBuilder.Entity("Bns.Domain.DataSources.DataSource", b =>
                {
                    b.HasOne("Bns.Domain.DataSources.DataSourceOlapConfig", "Configuration")
                        .WithMany()
                        .HasForeignKey("ConfigurationId");

                    b.Navigation("Configuration");
                });

            modelBuilder.Entity("Bns.Domain.Users.User", b =>
                {
                    b.HasOne("Bns.Domain.Users.UserSettings", "Settings")
                        .WithMany()
                        .HasForeignKey("SettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Settings");
                });

            modelBuilder.Entity("Bns.Domain.Users.UserSettings", b =>
                {
                    b.HasOne("Bns.Domain.Users.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId");

                    b.Navigation("Language");
                });
#pragma warning restore 612, 618
        }
    }
}
